# Generated by Django 3.0.8 on 2021-03-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('contact', models.CharField(blank=True, max_length=80, null=True)),
                ('qrcode', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
